#ifndef __APPCONFIG_H__
#define __APPCONFIG_H__

#define FIRMWARE_VERSION "1.5.3"

#define COMMAND_RECEIVED_MSG "COMMAND RECEIVED"

// #define RUN_TESTS
#define BTN_FORCE_RESEND_DELAY_SECONDS (180)
#define SEND_DATA_DIFF_INTERVAL_SECONDS (300)
#define SEND_DATA_ALL_INTERVAL_SECONDS (6 * 60 * 60) // 6 hours

#define LED_POWER (9)
#define LED_WIFI (10)
#define LED_MODBUS (11)
#define LED_4G (12)

#define NVS_INGELI_PROVISIONING_PART_NAME "provisioning"
#define NVS_INGELI_CONFIGS_PART_NAME "configs"
#define NVS_INGELI_HISTORY_PART_NAME "history"

#define MODBUS_READ_RETRY_COUNT (3)
#define MODBUS_DEVICE_SEARCH_RETRY (10)
#define MODBUS_READ_RETRY_DELAY (100)
#endif //__APPCONFIG_H__